### PR TITLE
feat: Support retry failure policy for event based functions

### LINKED ISSUE #131: Enable --retry flag for background functions
I started using Google Cloud Functions to subscribe to a pub/sub topic. The problem is, that by default Pub/Sub messages are acknowledged on receive and not when the function executed successfully.

If I would use the gcloud CLI for the deployment of the function, I would add the --retry flag.

Is it somehow possible to do that now?

As it is not possible to include this in the serverless.yml yet, I would suggest something like this:

```yml
functions:
  handlerNameFunction:
    handler: handlerName
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/:projectId/topics/:topic
          retry: true
``` 
with a default to false

or if we want to be able to also add future flags:
```yml
functions:
  handlerNameFunction:
    handler: handlerName
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/:projectId/topics/:topic
          flags:
            - retry
``` 

1) Is there a way to sneak this flag in already?
2) What do you think of the suggested addition?

Best,
Kalle

### PR DESCRIPTION
**Pull request by flaviomp**
Resolves #131 
```yaml
functions:
  pubsub-function:
    handler: processPubSub
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/my-topic
          failurePolicy:
            retry: {}
```

### CODE REVIEW

**Comment by frederikvanhevel** [comment]
Whats the status of this? I need to be able to set this flag. I would also like to specify the max instances like what is documented here: https://cloud.google.com/functions/docs/max-instances

**Comment by flaviomp** [comment]
@pgrzesik, based on the latest releases, I think you are the only maintainer for this project. Would you mind to take a look at this? Thanks.

**Comment by pgrzesik** [comment]
Thanks for pining me @flaviomp - I'm trying to unblock the PRs and push releases if possible, but honestly I'm no expert on Google Cloud itself. The proposed PR looks good though :+1:

**Review by pgrzesik — APPROVED** [review]

**Comment by oakesja** [comment]
@pgrzesik anyway we can get a new release for this change?

**Comment by pgrzesik** [comment]
Hey @oakesja :wave: It was just released with `4.3.0`

**Comment by engineforce** [comment]
Sorry, how to I pass `backoff` properties to the `retry` object? I cannot find any documentation what are the properties in this `retry` object?

**Pull request merged**
