### PR TITLE
A few unit tests

### PR DESCRIPTION
**Pull request by RomanGotsiy**
Started adding unit tests (#2)

### CODE REVIEW

**Comment by nikgraf** [comment]
nice, looks good to me 👌
@pmuens you better double-check as you know the code better :)

**Comment by pmuens** [comment]
Damn @RomanGotsiy you rock! 🎉 

Thanks for getting this started! I'll look into it ASAP!

**Comment by pmuens** [comment]
Hey @RomanGotsiy thank you very much for that!

I'll merge it now so that you appear as a contributor in the GitHub contributors list!
We'll re-write this plugin the upcoming days and will wipe out everything so that we have a blank slate. We'll write it in a way where we utilize the the official Node.js Google Cloud Functions package (see: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1688) in combination with the Google Deployment Manager for the needed infrastructure.

However we're constantly looking back at the stuff which was done here (some tings can be copied and pasted) and will use your tests as well.

So thanks again 🙌

**Comment by RomanGotsiy** [comment]
woohooo - that was fast 🚀 😂 
@pmuens thank you! You're so attentive 😄 

I'm happy that project is evolving 👍 
Will be happy to help with tests out in the future 🙌

**Comment by pmuens** [comment]
😄 yes, sorry for the slow response but we had some discussion how this project should evolve.

> Will be happy to help out with tests in the future

Awesome! That's good to hear. Thanks for offering help here 🙌

**Pull request merged**
