### PR TITLE
Migrate to CloudFunctions v1 API.

### PR DESCRIPTION
**Pull request by mather**
## Motivation

We should use v1 API asap.
> The Cloud Functions v1beta2 API is deprecated. To avoid potential service disruptions, please use the Cloud Functions v1 API instead.
https://cloud.google.com/functions/docs/api-migration

## Changes

- `location` property migrate to `parent`.
- Use `entryPoint` property to specify handler function.
- Use `function` property for stage-distinct function name to avoid confusion of function name in GCP console and confliction of `http` event endpoint URL.

### Related Issues

#105

### CODE REVIEW

**Comment by mather** [comment]
@pmuens Is this plugin no more maintained?

**Comment by davidjb99** [comment]
Would be good to get this merged...

**Comment by dee-me-tree-or-love** [comment]
Awesome, really looking forward to this! 
This would also then need the doc updates here right? 
https://serverless.com/framework/docs/providers/google/

**Comment by mather** [comment]
> This would also then need the doc updates here right?
> https://serverless.com/framework/docs/providers/google/

I think so.

**Comment by haflinger** [comment]
Hi, is this plugin maintained  ?

**Comment by sema4-bohdankostrytskyi** [comment]
Hey! Any update?

**Comment by paladiy** [comment]
Hey, are you planning to move this PR forward? Google is pushing people to migrate from beta API

**Comment by nahpeps** [comment]
@mather Any chance you solve the conflicts in this branch, so that it may can get finally merged?

**Comment by IamGabrielWu** [comment]
Can please help get it merged asap ?

**Comment by IamGabrielWu** [comment]
Google sent notification to force use v1.
Hello Google Cloud Functions Customer,

In June 2018, we announced Cloud Functions v1beta2 API version will be shut down on December 4, 2018. In order to give customers more time to migrate, we extended the deadline and we are now writing to let you know that the Google Cloud Functions v1beta2 API version will be shut down on April 15, 2020.

We are writing to remind you that your projects have recently made calls to the Cloud Functions v1beta2 API. Please upgrade to Cloud Functions v1 API by April 15, 2020. Google Cloud Functions v1 API has been available since October 2017.

**Comment by IamGabrielWu** [comment]
@mather can you please help resolve the conflicts and have this PR merged ?  we're in really need to use v1 cloudfunction.

**Comment by mather** [comment]
I have resolved conflicts. Anyone can review this PR?

**Comment by mather** [comment]
When do Coveralls finishes coverage tests...?

**Comment by medikoo** [comment]
@mather We're going to take this now. I understand it's a breaking change (?)

**Comment by mather** [comment]
It seems passed coverage tests already 🤔 
https://coveralls.io/builds/29518088

**Comment by IamGabrielWu** [comment]
Why it still says merging is blocked ? @KhadijaBenAmmar  @medikoo

**Comment by medikoo** [comment]
@IamGabrielWu I'm happy to merge and publish it now.

There's just one thing I want to be sure of:

I understand that it's a (semver wise) breaking change, and requires bump of major to v3 (?)

**Comment by mather** [comment]
@medikoo 
> requires bump of major to v3
Any problem like some feature (or bugfix) is ready and should be released soon?

**Comment by mather** [comment]
@medikoo 

> requires bump of major to v3 (?)

Umm. I think this is minor update because this update doesn't have any interface modification on user side.

**Comment by medikoo** [comment]
It's published with v2.4.2 Sorry for delay!

**Comment by paladiy** [comment]
@medikoo Thank you for moving this forward. 

I've already tried to upgrade to new version and got error: 

`Resource types cannot be changed, previous (cloudfunctions.v1beta2.function) -> updated (gcp-types/cloudfunctions-v1:projects.locations.functions)`

Googling around did not pointed to anything, but seems like it is because of the version change. Do you have any idea what could be a reason of this issue?

**Comment by medikoo** [comment]
> Do you have any idea what could be a reason of this issue?

It might be then that it requires creation of a stack from a start (I'm not that familiar with Google Cloud), but if it's the case. then this change should be reverted in context of v2, and published with v3 as breaking.

Before I do that, I'd love other users to confirm

**Comment by paladiy** [comment]
yes, seems like it is the case, I've just tried to deploy function with different name (meaning create new one) and it worked well. thx

**Comment by IamGabrielWu** [comment]
I deleted old stack completely and redeployed but i got below error.
It seems i need to specify region ? How to specify ?
`  Error --------------------------------------------------

  Error: Deployment failed: RESOURCE_ERROR

       {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied on 'locations/undefined' (or it may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/aftership-test/locations/undefined/functions","httpMethod":"POST"}}
      at throwErrorIfDeploymentFails (/Users/dzwu/gitspace/connectors-serverless-webhook-processor/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:71:11)
      at provider.request.then.response (/Users/dzwu/gitspace/connectors-serverless-webhook-processor/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:42:17)
      at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by mather** [comment]
> then this change should be reverted in context of v2, and published with v3 as breaking.

Sure.
Sorry for not considering migration in production environment.

**Comment by bao1018** [comment]
Thanks for the workaround, we will see any solution to fix that migration challenge  @paladiy

**Comment by IamGabrielWu** [comment]
anybody gets this error after 2nd time deployment using this v1 api ?
`     {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid JSON payload received. Unknown name \"location\" at 'function': Cannot find field.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"function","description":"Invalid JSON payload received. Unknown name \"location\" at 'function': Cannot find field."}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/<project name>/locations/us-central1/functions/<function name>","httpMethod":"PATCH"}}`

**Comment by IamGabrielWu** [comment]
I raised a PR [https://github.com/serverless/serverless-google-cloudfunctions/pull/204/files](url) for this

**Comment by xerosanyam** [comment]
Got error "The GCF v1beta2 API is deprecated"

Solved by
1. npm install serverless-google-cloudfunctions@latest
2. Following Option-1 of migration guide, from here: https://github.com/serverless/serverless-google-cloudfunctions/blob/HEAD/MIGRATION_GUIDE.md

**Pull request merged**
