### PR TITLE
fix: Fix deployment status when the function name is specified

### PR DESCRIPTION
**Pull request by knightdna**
* fixes the logic to get the function name in service
* handles the case when the specified function name contains dash
* adds test case

### CODE REVIEW

**Comment by IamGabrielWu** [comment]
I still got the error with your PR code @knightdna 
```
> sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "first"...
Serverless: Creating deployment...
Serverless: Checking deployment create progress...
..
Serverless: Done...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
................
Serverless: Done...

  Serverless Error ---------------------------------------

  Function "cf_test_pubsub_helloworld_python_usce1_v1" doesn't exist in this Service

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.13.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.3

>
```

**Comment by IamGabrielWu** [comment]
Turns out the handler has to be the same as the function name. It then works.
```
service: helloworld-python

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: aftership-dev
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: xxxx
plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  cf_test_pubsub_helloworld_python_usce1_v1:
    handler: http
    name: cf_test_pubsub_helloworld_python_usce1_v1
    events:
      - http: path
  # NOTE: the following uses an "event" event (pubSub event in this case).
  # Please create the corresponding resources in the Google Cloud
  # before deploying this service through Serverless
  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic
# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
#resources:
#  resources:
#    - type: storage.v1.bucket
#      name: my-serverless-service-bucket
#  imports:
#    - path: my_template.jinja

```

**Comment by IamGabrielWu** [comment]
@knightdna  I already made approval for changes. It seems still need a approving review. How can i make one ? Or anyone else can do it ?

**Comment by IamGabrielWu** [comment]
@medikoo  thanks for merging this. when will the fix be released ?

**Comment by medikoo** [comment]
@IamGabrielWu for release I believe we need to revert https://github.com/serverless/serverless-google-cloudfunctions/pull/219 as it brought the regression which was not addressed yet (handled here: https://github.com/serverless/serverless-google-cloudfunctions/pull/223)

Are you able to prepare a "Revert PR", usually GitHub provides button to do so at merged PR page, do you see it?

Having that fixed, we can go with release PR (merging this in will publish new version)

**Comment by knightdna** [comment]
Thanks a lot @IamGabrielWu for reviewing and approving this PR as well as @medikoo for merging it.

I can also help to prepare the revert PR.

**Pull request merged**
