### PR TITLE
Release 4.2.0

### PR DESCRIPTION
**Pull request by pgrzesik**

### CODE REVIEW

**Comment by CorentinDoue** [comment]
@pgrzesik I realized Travis URL has been changed the 15th of june
Screenshot from 2021-06-28 12-26-36
No Travis jobs have been triggered since then. You probably need to reconfigure the integration GitHub <=> Travis with a new webhook URL.

**Comment by pgrzesik** [comment]
Hey @CorentinDoue - we've identified similar thing, but as we're using Github Actions across our other repos, we'll be switching to Github Actions here as well - I plan to address it this week. Sorry for the delay and thanks for patience on this one

**Comment by CorentinDoue** [comment]
@pgrzesik Would you like some help migrating from Travis to Github actions? Would be happy to help with a PR if you want.

**Comment by pgrzesik** [comment]
Hello @CorentinDoue :wave: Sorry for dropping the ball on this one - it is on my list but I'm swamped with things that have a bit higher priority and I didn't got a chance to get to it yet. Any help would be much appreciated as I'm on short vacation till the end of this week - if you'd like to help out with implementation it would be much appreciated, here's our standard template: https://github.com/serverless/template-package/tree/master/.github/workflows

**Comment by pgrzesik** [comment]
Hey @CorentinDoue - sorry for the delay, new version should be out now.

**Comment by CorentinDoue** [comment]
Thank you 😁

**Pull request merged**
