### PR TITLE
feat: add support for environment variables in Cloud Functions

### PR DESCRIPTION
**Pull request by nethunter**
Add support for passing environment variables to a function

### CODE REVIEW

**Comment by vertexclique** [comment]
Can we merge this? If this is done?

**Comment by nethunter** [comment]
@vertexclique I've been using it for a couple of weeks now, with no problems. As far as I'm concerned, it definitely can be merged.

**Comment by vertexclique** [comment]
Let's do that then. Want to use it also from the upstream.

**Comment by tmilewski** [comment]
I'm using this, without issue, as well.

**Comment by vertexclique** [comment]
@pmuens Do you have time to take a look? Would be really nice to merge this and roll a patch.

**Comment by cirdes** [comment]
It would be nice to have this

**Comment by armand1m** [comment]
would love to see this merged 💖

**Comment by armand1m** [comment]
Is there any way to have this merged? Anything I can help with?

**Comment by armand1m** [comment]
cc @pmuens

I am having to come up with some hacks in order to have a proper cloud function configured by the CI pipelines due to this, is there anything I can do to help getting this merged?

**Comment by armand1m** [comment]
@nethunter this itself is already quite of a hack 😛 but I'll probably use this workaround by now.

**Comment by markmssd** [comment]
Nice PR!

I've done a little change to it, to allow merging the provider environments with the function ones:
```
      funcTemplate.properties.environmentVariables = _.merge(
        _.get(this, 'serverless.service.provider.environment'),
        funcObject.environment,
      );

      if (!_.size(funcTemplate.properties.environmentVariables)) {
        delete funcTemplate.properties.environmentVariables;
      }
```

👍

**Comment by nethunter** [comment]
@markmssd cool, I have added your change to my code, and added another unit test for this case as well

**Comment by cirdes** [comment]
I do agree with @armand1m , using the repo from another Github is quite a hack or at least far from ideal. I had to bundle the support for environment variables and distinct entryPoint #97  to be able to set more than one deployment stage. And its seems that there is a lot of people doing the same. I think that Google Cloud is nicer and more productive than AWS. It would be nice to see the serverless framework evolve the GCP support.

**Comment by nethunter** [comment]
@cirdes well, I would love to have this merged, but the last official merge to this repository was 1.5 months ago. It seems that the maintainers of this repo aren't very active. At this point, I'm thinking of taking over maintaining this repo, and just making a repo with all the open pull requests inside...

**Comment by armand1m** [comment]
HEY PLEASE MERGE THIS 

cc @pmuens 

PLEASE I BEG YOU

**Comment by kjanoudi** [comment]
Merge this pleaseeeee

**Comment by armand1m** [comment]
pls PLZZZZZZZZZZZ

**Comment by nethunter** [comment]
@pmuens cool, thanks!

**Comment by pmuens** [comment]
Alright. I just published the new version (`v2.1.0`) which includes this feature to npm (--> https://www.npmjs.com/package/serverless-google-cloudfunctions).

Thanks again for jumpin in here @nethunter 🎉

/cc @kjanoudi @armand1m @cirdes @markmssd @vertexclique @tmilewski @tume

**Comment by cirdes** [comment]
@pmuens, thanks so much for merging this PR. Unfortunately, I still can't go back to this repository because of lack of stage support. Functions in dev and prod have the same name and are overriding each other.

Based on #97  I had done my own implementation. At least we are halfway to go!

**Pull request merged**
